apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - name: myapp
        image: chrisreeves1/myapp
        ports:
        - containerPort: 5500

---

apiVersion: v1
kind: Service
metadata:
  name: myapp 
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - name: myapp
    protocol: TCP
    port: 80
    targetPort: 5500
